name: taxi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^14.0.0
  http: ^1.2.1
  provider: ^6.1.2
  modal_bottom_sheet: ^3.0.0
  loading_animation_widget: ^1.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imgbackgrounds/
